services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - COMPUTE_ADDR=compute-engine:50051
    depends_on:
      - postgres
      - compute-engine
  compute-engine:
    build:
      context: .
      dockerfile: compute-engine/Dockerfile
    ports:
      - "50051:50051"
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=gojob
      - POSTGRES_PASSWORD=gojob
      - POSTGRES_DB=gojob
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
